# SPDX-FileCopyrightText: 2026 Gundu Labs
# SPDX-License-Identifier: GPL-3.0-or-later

[package]
name = "gaze-core"
version.workspace = true
edition.workspace = true
description = "Shared configuration, D-Bus, and IR device library for Gaze"
categories.workspace = true
homepage.workspace = true
keywords.workspace = true
license.workspace = true
publish.workspace = true
readme.workspace = true
repository.workspace = true

[dependencies]
anyhow.workspace = true
libc.workspace = true
zbus.workspace = true
zvariant.workspace = true
serde = { workspace = true, features = ["derive"] }
serde_plain.workspace = true
tracing.workspace = true
toml_edit = { workspace = true, features = ["serde"] }
strum.workspace = true
strum_macros.workspace = true

[build-dependencies]
toml_edit = { workspace = true, features = ["serde"] }
serde = { workspace = true, features = ["derive"] }
